// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

const encoding0_enum = {
  info: 1,
  error: 2,
  debug: 3
}

// @wdk-core/log-type-enum enum
const encoding0 = {
  preencode (state, m) {
    state.end++ // max enum is 3 so always one byte
  },
  encode (state, m) {
    if (m > 3) throw new Error('Unknown enum')
    c.uint.encode(state, m)
  },
  decode (state) {
    return c.uint.decode(state)
  }
}

// @wdk-core/log-request
const encoding1 = {
  preencode (state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.type) encoding0.preencode(state, m.type)
    if (m.data) c.string.preencode(state, m.data)
  },
  encode (state, m) {
    const flags =
      (m.type ? 1 : 0) |
      (m.data ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.type) encoding0.encode(state, m.type)
    if (m.data) c.string.encode(state, m.data)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      type: (flags & 1) !== 0 ? encoding0.decode(state) : 0,
      data: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/workletStart-request
const encoding2 = {
  preencode (state, m) {
    state.end++ // max flag is 4 so always one byte

    if (m.enableDebugLogs) c.uint.preencode(state, m.enableDebugLogs)
    if (m.seedPhrase) c.string.preencode(state, m.seedPhrase)
    if (m.seedBuffer) c.string.preencode(state, m.seedBuffer)
    c.string.preencode(state, m.config)
  },
  encode (state, m) {
    const flags =
      (m.enableDebugLogs ? 1 : 0) |
      (m.seedPhrase ? 2 : 0) |
      (m.seedBuffer ? 4 : 0)

    c.uint.encode(state, flags)

    if (m.enableDebugLogs) c.uint.encode(state, m.enableDebugLogs)
    if (m.seedPhrase) c.string.encode(state, m.seedPhrase)
    if (m.seedBuffer) c.string.encode(state, m.seedBuffer)
    c.string.encode(state, m.config)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      enableDebugLogs: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      seedPhrase: (flags & 2) !== 0 ? c.string.decode(state) : null,
      seedBuffer: (flags & 4) !== 0 ? c.string.decode(state) : null,
      config: c.string.decode(state)
    }
  }
}

// @wdk-core/workletStart-response
const encoding3 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.status) c.string.preencode(state, m.status)
  },
  encode (state, m) {
    const flags = m.status ? 1 : 0

    c.uint.encode(state, flags)

    if (m.status) c.string.encode(state, m.status)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      status: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/getAddress-request
const encoding4 = {
  preencode (state, m) {
    c.string.preencode(state, m.network)
    c.uint.preencode(state, m.accountIndex)
  },
  encode (state, m) {
    c.string.encode(state, m.network)
    c.uint.encode(state, m.accountIndex)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)

    return {
      network: r0,
      accountIndex: r1
    }
  }
}

// @wdk-core/getAddress-response
const encoding5 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.address) c.string.preencode(state, m.address)
  },
  encode (state, m) {
    const flags = m.address ? 1 : 0

    c.uint.encode(state, flags)

    if (m.address) c.string.encode(state, m.address)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      address: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/getAddressBalance-request
const encoding6 = encoding4

// @wdk-core/getAddressBalance-response
const encoding7 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.balance) c.string.preencode(state, m.balance)
  },
  encode (state, m) {
    const flags = m.balance ? 1 : 0

    c.uint.encode(state, flags)

    if (m.balance) c.string.encode(state, m.balance)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      balance: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/quoteSendTransaction-request-options
const encoding8 = {
  preencode (state, m) {
    c.string.preencode(state, m.to)
    c.uint.preencode(state, m.value)
  },
  encode (state, m) {
    c.string.encode(state, m.to)
    c.uint.encode(state, m.value)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)

    return {
      to: r0,
      value: r1
    }
  }
}

// @wdk-core/quoteSendTransaction-request.options
const encoding9_2 = c.frame(encoding8)

// @wdk-core/quoteSendTransaction-request
const encoding9 = {
  preencode (state, m) {
    c.string.preencode(state, m.network)
    c.uint.preencode(state, m.accountIndex)
    encoding9_2.preencode(state, m.options)
  },
  encode (state, m) {
    c.string.encode(state, m.network)
    c.uint.encode(state, m.accountIndex)
    encoding9_2.encode(state, m.options)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = encoding9_2.decode(state)

    return {
      network: r0,
      accountIndex: r1,
      options: r2
    }
  }
}

// @wdk-core/quoteSendTransaction-response
const encoding10 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.fee) c.uint.preencode(state, m.fee)
  },
  encode (state, m) {
    const flags = m.fee ? 1 : 0

    c.uint.encode(state, flags)

    if (m.fee) c.uint.encode(state, m.fee)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      fee: (flags & 1) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @wdk-core/sendTransaction-request-options
const encoding11 = encoding8

// @wdk-core/sendTransaction-request.options
const encoding12_2 = c.frame(encoding11)

// @wdk-core/sendTransaction-request
const encoding12 = {
  preencode (state, m) {
    c.string.preencode(state, m.network)
    c.uint.preencode(state, m.accountIndex)
    encoding12_2.preencode(state, m.options)
  },
  encode (state, m) {
    c.string.encode(state, m.network)
    c.uint.encode(state, m.accountIndex)
    encoding12_2.encode(state, m.options)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = encoding12_2.decode(state)

    return {
      network: r0,
      accountIndex: r1,
      options: r2
    }
  }
}

// @wdk-core/sendTransaction-response
const encoding13 = {
  preencode (state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.fee) c.uint.preencode(state, m.fee)
    if (m.hash) c.string.preencode(state, m.hash)
  },
  encode (state, m) {
    const flags =
      (m.fee ? 1 : 0) |
      (m.hash ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.fee) c.uint.encode(state, m.fee)
    if (m.hash) c.string.encode(state, m.hash)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      fee: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      hash: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/getApproveTransaction-request
const encoding14 = {
  preencode (state, m) {
    c.string.preencode(state, m.token)
    c.string.preencode(state, m.recipient)
    c.uint.preencode(state, m.amount)
  },
  encode (state, m) {
    c.string.encode(state, m.token)
    c.string.encode(state, m.recipient)
    c.uint.encode(state, m.amount)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.uint.decode(state)

    return {
      token: r0,
      recipient: r1,
      amount: r2
    }
  }
}

// @wdk-core/getApproveTransaction-response
const encoding15 = {
  preencode (state, m) {
    c.string.preencode(state, m.to)
    c.uint.preencode(state, m.value)
    c.string.preencode(state, m.data)
  },
  encode (state, m) {
    c.string.encode(state, m.to)
    c.uint.encode(state, m.value)
    c.string.encode(state, m.data)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.string.decode(state)

    return {
      to: r0,
      value: r1,
      data: r2
    }
  }
}

// @wdk-core/getTransactionReceipt-request
const encoding16 = {
  preencode (state, m) {
    c.string.preencode(state, m.network)
    c.uint.preencode(state, m.accountIndex)
    c.string.preencode(state, m.hash)
  },
  encode (state, m) {
    c.string.encode(state, m.network)
    c.uint.encode(state, m.accountIndex)
    c.string.encode(state, m.hash)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.string.decode(state)

    return {
      network: r0,
      accountIndex: r1,
      hash: r2
    }
  }
}

// @wdk-core/getTransactionReceipt-response
const encoding17 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.receipt) c.string.preencode(state, m.receipt)
  },
  encode (state, m) {
    const flags = m.receipt ? 1 : 0

    c.uint.encode(state, flags)

    if (m.receipt) c.string.encode(state, m.receipt)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      receipt: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/dispose-request
const encoding18 = {
  preencode (state, m) {

  },
  encode (state, m) {

  },
  decode (state) {
    return {
    }
  }
}

function setVersion (v) {
  version = v
}

function encode (name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode (name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum (name) {
  switch (name) {
    case '@wdk-core/log-type-enum': return encoding0_enum
    default: throw new Error('Enum not found ' + name)
  }
}

function getEncoding (name) {
  switch (name) {
    case '@wdk-core/log-type-enum': return encoding0
    case '@wdk-core/log-request': return encoding1
    case '@wdk-core/workletStart-request': return encoding2
    case '@wdk-core/workletStart-response': return encoding3
    case '@wdk-core/getAddress-request': return encoding4
    case '@wdk-core/getAddress-response': return encoding5
    case '@wdk-core/getAddressBalance-request': return encoding6
    case '@wdk-core/getAddressBalance-response': return encoding7
    case '@wdk-core/quoteSendTransaction-request-options': return encoding8
    case '@wdk-core/quoteSendTransaction-request': return encoding9
    case '@wdk-core/quoteSendTransaction-response': return encoding10
    case '@wdk-core/sendTransaction-request-options': return encoding11
    case '@wdk-core/sendTransaction-request': return encoding12
    case '@wdk-core/sendTransaction-response': return encoding13
    case '@wdk-core/getApproveTransaction-request': return encoding14
    case '@wdk-core/getApproveTransaction-response': return encoding15
    case '@wdk-core/getTransactionReceipt-request': return encoding16
    case '@wdk-core/getTransactionReceipt-response': return encoding17
    case '@wdk-core/dispose-request': return encoding18
    default: throw new Error('Encoder not found ' + name)
  }
}

function getStruct (name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode (state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode (state, m) {
      version = v
      enc.encode(state, m)
    },
    decode (state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
